/*=============================================================================
 
indirect_indexing.inc

#included in test_utilities.cpp

Peter Hakel
Los Alamos National Laboratory
XCP-5 group

Created on 7 July 2015
Last modified on 28 January 2020

Copyright (c) 2015, Triad National Security, LLC.
All rights reserved.
Use of this source code is governed by the BSD 3-Clause License.
See top-level license.txt file for full license text.

CODE NAME:  FESTR, Version 0.8 (C15068)
Classification Review Number: LA-CC-15-045
Export Control Classification Number (ECCN): EAR99
B&R Code:  DP1516090

=============================================================================*/

std::vector<size_t> dim; // dimensions
dim.push_back(4); // dimension #0
dim.push_back(2); // dimension #1
dim.push_back(1); // dimension #2
dim.push_back(3); // dimension #3

//  end indirect_indexing.inc
