/*=============================================================================
 
integ_trap.inc

#included in test_utilities.cpp

Tabulated function: (1,2) (3,8) (6,6) (7,0)

Peter Hakel
Los Alamos National Laboratory
XCP-5 group

Created on 27 July 2015
Last modified on 28 January 2020

Copyright (c) 2015, Triad National Security, LLC.
All rights reserved.
Use of this source code is governed by the BSD 3-Clause License.
See top-level license.txt file for full license text.

CODE NAME:  FESTR, Version 0.8 (C15068)
Classification Review Number: LA-CC-15-045
Export Control Classification Number (ECCN): EAR99
B&R Code:  DP1516090

=============================================================================*/

const size_t n = 4;
double x[n] = {1.0, 3.0, 6.0, 7.0};
double y[n] = {2.0, 8.0, 6.0, 0.0};

//  end integ_trap.inc
