/*=============================================================================
 
is_contained_in.inc

#included in test_utilities.cpp

Peter Hakel
Los Alamos National Laboratory
XCP-5 group

Created on 25 October 2015
Last modified on 3 March 2019

Copyright (c) 2015, Triad National Security, LLC.
All rights reserved.
Use of this source code is governed by the BSD 3-Clause License.
See top-level license.txt file for full license text.

CODE NAME:  FESTR, Version 0.8 (C15068)
Classification Review Number: LA-CC-15-045
Export Control Classification Number (ECCN): EAR99
B&R Code:  DP1516090

=============================================================================*/

std::vector< std::pair<double, double> > intervals;
intervals.push_back( std::make_pair(3.0, 5.0) );
intervals.push_back( std::make_pair(8.0, 9.0) );

// end is_contained_in.inc
