/*=============================================================================
 
table.inc

#included in test_utilities.cpp

A monotonically increasing set of values stored in vector<double>

Peter Hakel
Los Alamos National Laboratory
XCP-5 group

Created on 1 January 2015
Last modified on 3 March 2019

Copyright (c) 2015, Triad National Security, LLC.
All rights reserved.
Use of this source code is governed by the BSD 3-Clause License.
See top-level license.txt file for full license text.

CODE NAME:  FESTR, Version 0.8 (C15068)
Classification Review Number: LA-CC-15-045
Export Control Classification Number (ECCN): EAR99
B&R Code:  DP1516090

=============================================================================*/

std::vector<double> v;
v.push_back(0.3); //  0
v.push_back(0.5); //  1
v.push_back(0.9); //  2
v.push_back(1.1); //  3
v.push_back(1.8); //  4
v.push_back(2.0); //  5
v.push_back(2.1); //  6
v.push_back(2.4); //  7
v.push_back(2.6); //  8
v.push_back(2.7); //  9
v.push_back(2.9); // 10
v.push_back(3.4); // 11
v.push_back(4.4); // 12
v.push_back(5.4); // 13
v.push_back(5.5); // 14
v.push_back(5.9); // 15
v.push_back(6.1); // 16
v.push_back(6.4); // 17
v.push_back(6.6); // 18
v.push_back(7.0); // 19
v.push_back(7.4); // 20
v.push_back(8.0); // 21
v.push_back(8.2); // 22
v.push_back(8.3); // 23
v.push_back(8.6); // 24
v.push_back(8.9); // 25
v.push_back(9.0); // 26
v.push_back(9.5); // 27
v.push_back(9.6); // 28
v.push_back(9.9); // 29

// end table.inc
